language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
before_install:
  - sudo apt-get install libxml2-utils
  - pip install -U setuptools
  - pip install pynlpl
install: 
  - python setup.py install
script:  
  - cd test && bash test.sh
