language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true
before_install:
  - sudo apt-get install libxml2-utils
  - pip install -U setuptools
  - pip install pynlpl
install:
  - python setup.py install
script:
  - cd test && bash test.sh
